In [1]:
import numpy as np
import pandas as pd
import nltk
from string import punctuation
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.decomposition import PCA

In [2]:
raw_data = pd.read_csv("IPL_Ball_by_Ball_2008_2022.csv")
raw_data = raw_data.sample(frac=0.1, random_state=42)
raw_data

ID  innings  overs  ballnumber       batter         bowler  \
177814   501226        1     12           2     MS Dhoni   Yuvraj Singh   
3287    1304107        1     17           4  SW Billings    T Natarajan   
188612   419148        2     13           3   RV Uthappa     AD Mathews   
96212    980961        1     13           6    RA Jadeja         Z Khan   
30637   1254064        1      5           1      RR Pant     JD Unadkat   
...         ...      ...    ...         ...          ...            ...   
164073   548320        2     16           4    YK Pathan        GB Hogg   
29125   1254071        2     14           1  JM Bairstow       FA Allen   
84133   1082612        1      9           4      WP Saha      JJ Bumrah   
164546   548318        2     16           5     MS Dhoni  R Vinay Kumar   
137734   598047        2      9           3    AM Rahane     AD Mathews   

            non-striker extra_type  batsman_run  extras_run  total_run  \
177814       MEK Hussey        NaN            1           0          1   
3287         AD Russell        NaN            6           0          6   
188612      LRPL Taylor        NaN            0           0          0   
96212        KD Karthik        NaN            0           0          0   
30637         AM Rahane        NaN            4           0          4   
...                 ...        ...          ...         ...        ...   
164073  Shakib Al Hasan        NaN            0           0          0   
29125     KS Williamson        NaN            1           0          1   
84133           HM Amla        NaN            2           0          2   
164546         DJ Bravo        NaN            0           0          0   
137734         R Dravid        NaN            1           0          1   

        non_boundary  isWicketDelivery player_out kind fielders_involved  \
177814             0                 0        NaN  NaN               NaN   
3287               0                 0        NaN  NaN               NaN   
188612             0                 0        NaN  NaN               NaN   
96212              0                 0        NaN  NaN               NaN   
30637              0                 0        NaN  NaN               NaN   
...              ...               ...        ...  ...               ...   
164073             0                 0        NaN  NaN               NaN   
29125              0                 0        NaN  NaN               NaN   
84133              0                 0        NaN  NaN               NaN   
164546             0                 0        NaN  NaN               NaN   
137734             0                 0        NaN  NaN               NaN   

                        BattingTeam  
177814          Chennai Super Kings  
3287          Kolkata Knight Riders  
188612  Royal Challengers Bangalore  
96212                 Gujarat Lions  
30637                Delhi Capitals  
...                             ...  
164073        Kolkata Knight Riders  
29125           Sunrisers Hyderabad  
84133               Kings XI Punjab  
164546          Chennai Super Kings  
137734             Rajasthan Royals  

[22595 rows x 17 columns]

In [3]:
def rectify_data(raw_data):
    raw_data=raw_data[raw_data['total_run']<=6]
    processed_data = pd.DataFrame()
    processed_data['first_innings'] = 2-raw_data['innings']
    processed_data['second_innings'] = raw_data['innings']-1
    processed_data['powerplay'] = (raw_data['overs']<=6).astype(int)
    processed_data['middle'] = ((raw_data['overs']>6) & (raw_data['overs']<=15)).astype(int)
    processed_data['death'] = (raw_data['overs']>15).astype(int)
    distinct_batters = raw_data['batter'].unique()
    batter_names = pd.concat([raw_data['batter'].fillna('') == batter for batter in distinct_batters], axis=1).astype(int)
    batter_names.columns = distinct_batters
    processed_data = pd.concat([processed_data,batter_names],axis=1)
    distinct_bowlers = raw_data['bowler'].unique()
    bowler_names = pd.concat([raw_data['bowler'].fillna('') == bowler for bowler in distinct_bowlers], axis=1).astype(int)
    bowler_names.columns = distinct_bowlers
    processed_data = pd.concat([processed_data,batter_names],axis=1)
    # processed_data['run_and_wicket'] = raw_data[['total_run','isWicketDelivery']].apply(list,axis=1)
    processed_data['label'] = raw_data['total_run']+7*raw_data['isWicketDelivery']    
    return processed_data

In [4]:
# def rectify_data(raw_data):
#     raw_data=raw_data[raw_data['total_run']<=6]
#     processed_data = pd.DataFrame()
#     processed_data['first_innings'] = 2-raw_data['innings']
#     processed_data['second_innings'] = raw_data['innings']-1
#     processed_data['powerplay'] = (raw_data['overs']<=6).astype(int)
#     processed_data['middle'] = ((raw_data['overs']>6) & (raw_data['overs']<=15)).astype(int)
#     processed_data['death'] = (raw_data['overs']>15).astype(int)
#     distinct_batters = {}
#     counter = 0
#     for i in raw_data['batter'].unique() :
#         distinct_batters[i]=counter
#         counter+=1
#     processed_data['batter'] = [distinct_batters[x] for x in raw_data['batter']]
#     distinct_bowlers = {}
#     counter = 0
#     for i in raw_data['bowler'].unique() :
#         distinct_bowlers[i]=counter
#         counter+=1
#     processed_data['bowler'] = [distinct_bowlers[x] for x in raw_data['bowler']]
#     # processed_data['total_run'] = raw_data['total_run']
#     # processed_data['iswicket'] = raw_data['isWicketDelivery']
#     processed_data['label'] = raw_data['total_run']+7*raw_data['isWicketDelivery']
#     return processed_data

In [5]:
modified_data = rectify_data(raw_data)
X = modified_data.drop(columns = "label")
Y = modified_data["label"]
len(modified_data.columns)

1070

In [6]:
pca = PCA(n_components=100) 
X = pca.fit_transform(X)     
pca.explained_variance_ratio_,sum(pca.explained_variance_ratio_)

(array([0.16259857, 0.13126957, 0.07079568, 0.01461266, 0.01374125,
        0.01307626, 0.01237963, 0.01137684, 0.01121262, 0.01102235,
        0.01056392, 0.01015152, 0.01000599, 0.00976529, 0.00970935,
        0.00928315, 0.00826755, 0.00813096, 0.00785032, 0.00774162,
        0.0075144 , 0.0071963 , 0.00703483, 0.0069368 , 0.00678653,
        0.00666877, 0.0062577 , 0.00608423, 0.00595508, 0.00590308,
        0.00579637, 0.00568504, 0.00566275, 0.00561036, 0.00552958,
        0.00547096, 0.00539912, 0.00528916, 0.00524449, 0.00514248,
        0.00513417, 0.00509051, 0.00505698, 0.00502526, 0.00488291,
        0.00480445, 0.00475349, 0.00461422, 0.0045405 , 0.00442212,
        0.00434431, 0.00424603, 0.00408169, 0.00391382, 0.00389424,
        0.00387153, 0.00383679, 0.00378969, 0.00373582, 0.00369518,
        0.00365028, 0.00360809, 0.00351042, 0.00343222, 0.00325279,
        0.00311639, 0.00304061, 0.0030012 , 0.00295013, 0.00289274,
        0.00280899, 0.00278374, 0.00271951, 0.00

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state = 1092003)

In [8]:
def Logistic_Regression(X_train,Y_train):
    model = LogisticRegression()
    model.fit(X_train,Y_train)
    return model

In [9]:
def SVM(X_train,Y_train):
    model = SVC()
    model.fit(X_train,Y_train)
    return model

In [10]:
def MLP(X_train,Y_train):
    model = MLPClassifier(activation = 'relu',hidden_layer_sizes=(10,5,10), max_iter=30000)
    model.fit(X_train,Y_train)
    return model

In [11]:
print("Using Logistic Regression :-")
model = Logistic_Regression(X_train,Y_train)
Y_train_pred = model.predict(X_train)
Y_test_pred = model.predict(X_test)
print("Accuracy on Trained data - ",accuracy_score(Y_train,Y_train_pred))
print("Classification report on Trained data - \n",classification_report(Y_train,Y_train_pred))
print("Confusion matrix on Trained data - \n",confusion_matrix(Y_train,Y_train_pred))
print("Accuracy on Test data - ",accuracy_score(Y_test,Y_test_pred))
print("Classification report on Test data - \n",classification_report(Y_test,Y_test_pred))
print("Confusion matrix on Test data - \n",confusion_matrix(Y_test,Y_test_pred))

Using Logistic Regression :-
Accuracy on Trained data -  0.44328870200287707
Classification report on Trained data - 
               precision    recall  f1-score   support

           0       0.42      0.37      0.39      5472
           1       0.45      0.80      0.58      7506
           2       0.00      0.00      0.00      1225
           3       0.00      0.00      0.00        56
           4       0.00      0.00      0.00      2073
           5       0.00      0.00      0.00        26
           6       0.00      0.00      0.00       813
           7       0.00      0.00      0.00       868
           8       0.00      0.00      0.00        33
           9       0.00      0.00      0.00         2

    accuracy                           0.44     18074
   macro avg       0.09      0.12      0.10     18074
weighted avg       0.31      0.44      0.36     18074

Confusion matrix on Trained data - 
 [[2001 3471    0    0    0    0    0    0    0    0]
 [1495 6011    0    0    0    0 

/opt/homebrew/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in l

In [12]:
i = 0
probabilities = model.predict_proba(X_test)
classes = model.classes_
dict = {}
for _ in range(len(classes)):
    print(_)
    dict[classes[_]] = probabilities[i][_]
dict

0
1
2
3
4
5
6
7
8
9


{0: 0.3500687636106078,
 1: 0.38707633175685163,
 2: 0.05029649145930744,
 3: 0.0012051486573527352,
 4: 0.1596167782300935,
 5: 0.0010134638945162517,
 6: 0.007169271783254197,
 7: 0.04263546717686471,
 8: 0.0008367101000912815,
 9: 8.157333106047672e-05}

In [13]:
num = model.predict_proba(X_test)
num[0]

array([3.50068764e-01, 3.87076332e-01, 5.02964915e-02, 1.20514866e-03,
       1.59616778e-01, 1.01346389e-03, 7.16927178e-03, 4.26354672e-02,
       8.36710100e-04, 8.15733311e-05])

In [14]:
print("Using SVM :-")
model = SVM(X_train,Y_train)
Y_train_pred = model.predict(X_train)
Y_test_pred = model.predict(X_test)
print("Accuracy on Trained data - ",accuracy_score(Y_train,Y_train_pred))
print("Classification report on Trained data - \n",classification_report(Y_train,Y_train_pred))
print("Confusion matrix on Trained data - \n",confusion_matrix(Y_train,Y_train_pred))
print("Accuracy on Test data - ",accuracy_score(Y_test,Y_test_pred))
print("Classification report on Test data - \n",classification_report(Y_test,Y_test_pred))
print("Confusion matrix on Test data - \n",confusion_matrix(Y_test,Y_test_pred))

Using SVM :-
Accuracy on Trained data -  0.45396702445501824
Classification report on Trained data - 
               precision    recall  f1-score   support

           0       0.43      0.41      0.42      5472
           1       0.46      0.79      0.58      7506
           2       1.00      0.00      0.00      1225
           3       0.00      0.00      0.00        56
           4       0.50      0.00      0.00      2073
           5       0.00      0.00      0.00        26
           6       0.00      0.00      0.00       813
           7       0.00      0.00      0.00       868
           8       0.00      0.00      0.00        33
           9       0.00      0.00      0.00         2

    accuracy                           0.45     18074
   macro avg       0.24      0.12      0.10     18074
weighted avg       0.45      0.45      0.37     18074

Confusion matrix on Trained data - 
 [[2242 3230    0    0    0    0    0    0    0    0]
 [1549 5956    0    0    1    0    0    0    0  

/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/lib/python3.11/site-packages/sklearn/metr

In [15]:
print("Using MLP :-")
model = MLP(X_train,Y_train)
Y_train_pred = model.predict(X_train)
Y_test_pred = model.predict(X_test)
print("Accuracy on Trained data - ",accuracy_score(Y_train,Y_train_pred))
print("Classification report on Trained data - \n",classification_report(Y_train,Y_train_pred))
print("Confusion matrix on Trained data - \n",confusion_matrix(Y_train,Y_train_pred))
print("Accuracy on Test data - ",accuracy_score(Y_test,Y_test_pred))
print("Classification report on Test data - \n",classification_report(Y_test,Y_test_pred))
print("Confusion matrix on Test data - \n",confusion_matrix(Y_test,Y_test_pred))

Using MLP :-
Accuracy on Trained data -  0.4473829810777913
Classification report on Trained data - 
               precision    recall  f1-score   support

           0       0.41      0.47      0.44      5472
           1       0.47      0.73      0.57      7506
           2       0.00      0.00      0.00      1225
           3       0.00      0.00      0.00        56
           4       0.00      0.00      0.00      2073
           5       0.00      0.00      0.00        26
           6       0.29      0.00      0.00       813
           7       0.00      0.00      0.00       868
           8       0.00      0.00      0.00        33
           9       0.00      0.00      0.00         2

    accuracy                           0.45     18074
   macro avg       0.12      0.12      0.10     18074
weighted avg       0.33      0.45      0.37     18074

Confusion matrix on Trained data - 
 [[2584 2887    0    0    0    0    1    0    0    0]
 [2006 5500    0    0    0    0    0    0    0   

/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/homebrew/lib/python3.11/site-packages/sklearn/metr